[gwrite.idraw2]
# a set of configuration parameters for the idraw v2.0
# these have largely been derived by monitoring how the inkscape idraw software communicates with the
# plotter by dumping the plotter commands to a debug file in the inkscape extension
unit = "mm"
vertical_flip = true

# set to mm, remember where we start, then
# ensure the pen is lifted and set the pen up travel speed
document_start = """G21\nG92 X0 Y0\nG1G90 Z0.5F20000\nG1 F8000\n"""

# travel to the start of a segment using negative relative coords then
# lower a pen to absolute position z=5 and configure the pen down speed to 2000
segment_first = """G1G91X{_dx:.3f}Y{_dy:.3f}\nG1G90 Z5.0F5000\nG1 F2000\n"""
# draw to negative relative position
segment = "G1G91X{_dx:.3f}Y{_dy:.3f}\n"
# draw to negative relative position then
# lift a pen to absolute position z=0.5 and configure the pen up speed to 8000
segment_last = """G1G91X{_dx:.3f}Y{_dy:.3f}\nG1G90 Z0.5F20000\nG1 F8000\n"""

# at the end of the document, move to where we started and then sleep to de-enegerise the steppers
document_end = """G90G0 X0 Y0\n$SLP\n"""
